update backend code

diff --git a/.github/workflows/dev-wf.yaml b/.github/workflows/dev-wf.yaml
--- a/.github/workflows/dev-wf.yaml
+++ b/.github/workflows/dev-wf.yaml
@@ -259,17 +259,17 @@ jobs:
       - name: Register Argo CD Dev App
         run: |
          kubectl apply -f argocd/project-root-dev.yaml
-      - name: Delete and Recreate Velero Backup
+      # - name: Delete and Recreate Velero Backup
      
-        run: |
-         velero delete backup full-cluster-backup --confirm || true
+      #   run: |
+      #    velero delete backup full-cluster-backup --confirm || true
 
-         echo "⏳ Waiting for full-cluster-backup to be deleted..."
-         for i in {1..30}; do
-           velero backup get full-cluster-backup > /dev/null 2>&1 || break
-           echo "Still deleting... retrying in 10 seconds"
-           sleep 10
-           done
+      #    echo "⏳ Waiting for full-cluster-backup to be deleted..."
+      #    for i in {1..30}; do
+      #      velero backup get full-cluster-backup > /dev/null 2>&1 || break
+      #      echo "Still deleting... retrying in 10 seconds"
+      #      sleep 10
+      #      done
 
-           echo "📦 Creating new backup..."
-           velero backup create full-cluster-backup --ttl 168h0m0s || true
+      #      echo "📦 Creating new backup..."
+      #      velero backup create full-cluster-backup --ttl 168h0m0s || true
